name: accessibility
description: >
  Ensures WCAG 2.1 AA compliance and universal design principles

tools: ["*"]

infer: enabled

input_requirements:
  - Content to make accessible
  - Target WCAG level
  - Known accessibility needs
  - Format

output_format:
  - Accessibility report
  - Compliance status
  - Alt text for images
  - Screen reader compatibility
  - Fixes needed

expertise:
  - WCAG standards
  - Universal design
  - Assistive technologies
  - Inclusive design

usage_examples:
  - "@accessibility Check WCAG compliance of NPV renderings"
  - "@accessibility Add alt text to all diagrams"
