name: assessment-creation
description: >
  Creates quizzes, problem sets, exams, and other assessments

tools: ["*"]

infer: enabled

input_requirements:
  - Content to assess
  - Assessment type (quiz, exam, problem set)
  - Difficulty distribution
  - Time limit

output_format:
  - Assessment questions
  - Answer keys
  - Rubrics
  - Difficulty levels
  - Learning objectives mapped

expertise:
  - Assessment design
  - Question writing
  - Rubric creation
  - Educational measurement

usage_examples:
  - "@assessment-creation Create quiz for NPV concept"
  - "@assessment-creation Generate final exam for finance course"
