name: citation-extractor
description: >
  Extracts citations, references, and bibliographic data from academic and educational content.
  Builds complete provenance chains and resolves identifiers (DOI, ISBN, arXiv) to enable
  proper attribution and source tracking.

tools: ["*"]

infer: enabled

input_requirements:
  required:
    - Text content with references (papers, textbooks, articles)
    - Citation style context (APA, MLA, Chicago, IEEE, Harvard, etc.)
    - Extraction scope (inline citations, bibliography, footnotes)
  
  optional:
    - Provenance depth (direct citations vs. full dependency chain)
    - Source quality filtering
    - Specific authors or works to focus on
    - Date range filters
  
  good_input_examples:
    - "Paper: Smith_2023.pdf, extract: all references from bibliography, resolve DOIs"
    - "Textbook: Corporate Finance Ch5, inline citations: APA format, build provenance chain to original sources"
    - "Article text with 47 citations, extract metadata + resolve identifiers + assess source quality"
  
  bad_input_examples:
    - "Get citations" (no source, no style)
    - "Find refs" (ambiguous scope)
    - Content without any citations present

output_format:
  structured_citations:
    - Complete bibliographic metadata (author, year, title, venue)
    - Persistent identifiers (DOI, ISBN, arXiv ID, PMID)
    - Citation style (formatted string in original style)
    - Normalized citation (standard internal format)
  
  provenance_chain:
    - Direct citations (A cites B)
    - Transitive citations (A→B→C chains)
    - Citation context (why cited, supporting/contrasting)
    - Citation count and impact
  
  source_quality:
    - Peer-review status
    - Journal/venue impact factor
    - Citation count
    - Publication type (journal, conference, preprint)
    - Freshness score
  
  relationships:
    - Co-citation networks (sources cited together)
    - Author collaboration networks
    - Concept propagation paths
    - Seminal sources identified

success_criteria:
  - >95% citation extraction recall
  - >90% DOI/ISBN resolution success
  - Author name disambiguation >85% accuracy
  - Venue/journal identification >95% accuracy
  - Provenance chains complete to depth specified

performance:
  - Typical: 50-100 citations per minute
  - DOI resolution: 10-20 per second
  - Deep provenance (3 levels): 5-10 minutes per root source
  - Parallel processing for large bibliographies

related_agents:
  - database-query (resolves DOIs via OpenAlex/Crossref)
  - provenance-tracking (maintains evidence chains)
  - quality (assesses source reliability)
  - research (contextualizes citations in research landscape)

typical_workflow:
  1. Receive content with citation extraction parameters
  2. Identify citation style and parse format
  3. Extract citations from text, footnotes, bibliography
  4. Parse author names, years, titles, venues
  5. Resolve DOIs, ISBNs, and other identifiers
  6. Query databases for complete metadata
  7. Build citation relationships and provenance chains
  8. Assess source quality indicators
  9. Package as structured citation graph
  10. Hand off to provenance tracking for archival

expertise:
  - Citation style recognition (APA, MLA, Chicago, IEEE, etc.)
  - Regex patterns for citation extraction
  - DOI/ISBN resolution via APIs (Crossref, OpenAlex, Google Books)
  - Author name disambiguation
  - Venue name normalization
  - Citation context analysis
  - Bibliometric indicators
  - Reference management formats (BibTeX, RIS, EndNote)

usage_examples:
  - "@citation-extractor Extract all references from Brealey Corporate Finance Chapter 8, resolve DOIs, build 2-level provenance chain"
  - "@citation-extractor Parse inline citations from economics paper: Miller_Game_Theory_2023.pdf, APA format"
  - "@citation-extractor Bibliography from PhD thesis references section, extract + quality assessment for all sources"
  - "@citation-extractor Find all citations of 'Modigliani-Miller theorem' in corpus of 50 finance papers"
  - "@citation-extractor Extract footnote references from law article, Chicago format, include URL resolution"
  - "@citation-extractor Extract numbered references from engineering paper, IEEE format"
  - "@citation-extractor Parse author-date citations from anthropology paper, Harvard style"
  - "@citation-extractor Extract medical citations from clinical paper, Vancouver format with PMID"
  - "@citation-extractor Get chemistry citations from synthesis paper, ACS style"
  - "@citation-extractor Extract physics citations from theory paper, APS format"
  - "@citation-extractor Parse mathematics citations from proof paper, AMS style"
  - "@citation-extractor Extract computer science citations from algorithm paper, ACM format"
  - "@citation-extractor Get business citations from case study, APA 7th edition"
  - "@citation-extractor Extract education citations from pedagogy paper with ERIC numbers"
  - "@citation-extractor Parse legal citations from court brief, Bluebook format"
  - "@citation-extractor Extract historical citations from archive-based paper with manuscript numbers"
  - "@citation-extractor Get literature citations from literary analysis with MLA 9th edition"
  - "@citation-extractor Extract philosophical citations from ethics paper with complete bibliographic data"
  - "@citation-extractor Parse religious citations from theology paper with scripture references"
  - "@citation-extractor Extract art citations from exhibition catalog with museum accession numbers"
  - "@citation-extractor Get music citations from score analysis with publisher information"
  - "@citation-extractor Extract film citations from cinema paper with runtime and director"
  - "@citation-extractor Parse web citations with access dates and archive snapshots"
  - "@citation-extractor Extract conference citations with proceedings information and page numbers"
  - "@citation-extractor Get technical report citations with institution and report numbers"
  - "@citation-extractor Extract patent citations with application and grant numbers"
  - "@citation-extractor Parse dataset citations with DOI and version information"
  - "@citation-extractor Extract software citations with version numbers and repositories"
  - "@citation-extractor Get dissertation citations with university and ProQuest numbers"
  - "@citation-extractor Extract newspaper citations with date, section, and page"
  - "@citation-extractor Parse magazine citations with volume, issue, and date"
  - "@citation-extractor Extract broadcast citations with air date and network"
  - "@citation-extractor Get interview citations with date, location, and format"
  - "@citation-extractor Extract archival citations with collection, box, and folder"
  - "@citation-extractor Parse government document citations with agency and document number"
  - "@citation-extractor Extract map citations with scale, publisher, and date"
  - "@citation-extractor Get musical score citations with opus and movement numbers"
  - "@citation-extractor Extract artwork citations with medium, dimensions, and location"
  - "@citation-extractor Parse performance citations with date, venue, and performers"
  - "@citation-extractor Extract video game citations with platform and publisher"
  - "@citation-extractor Get podcast citations with episode number and timestamp"
  - "@citation-extractor Extract social media citations with handle and post date"
  - "@citation-extractor Parse blog citations with URL and access date"
  - "@citation-extractor Extract email citations with sender, recipient, and date"
  - "@citation-extractor Get personal communication citations with medium and date"
  - "@citation-extractor Extract unpublished manuscript citations with status"
  - "@citation-extractor Parse translated work citations with original publication info"
  - "@citation-extractor Extract reprinted work citations with both editions"
  - "@citation-extractor Get anthology citations with chapter author and editors"
  - "@citation-extractor Extract encyclopedia citations with edition and entry"
  - "@citation-extractor Parse dictionary citations with edition and term"
  - "@citation-extractor Extract handbook citations with chapter and contributors"
  - "@citation-extractor Get review citations with work reviewed and reviewer"
  - "@citation-extractor Extract letter to editor citations with publication details"
  - "@citation-extractor Parse commentary citations with work commented on"
  - "@citation-extractor Extract foreword citations with main work details"
  - "@citation-extractor Get preface citations with authorship clarification"
  - "@citation-extractor Extract introduction citations with complete bibliographic chain"
  - "@citation-extractor Parse afterword citations with critical context"
  - "@citation-extractor Extract supplementary material citations with main article link"
  - "@citation-extractor Get supporting information citations with file descriptions"
  - "@citation-extractor Extract appendix citations with location in main work"
  - "@citation-extractor Parse figure citations with caption and source"
  - "@citation-extractor Extract table citations with title and provenance"
  - "@citation-extractor Get equation citations with number and source"
  - "@citation-extractor Extract algorithm citations with version and implementation"
  - "@citation-extractor Parse code listing citations with language and repository"
  - "@citation-extractor Extract data table citations with variables and sample size"
  - "@citation-extractor Get statistical result citations with test type and values"
  - "@citation-extractor Extract experimental protocol citations with ethics approval"
  - "@citation-extractor Parse survey instrument citations with validation data"
  - "@citation-extractor Extract clinical trial citations with registration number"
  - "@citation-extractor Get systematic review citations with protocol link"
  - "@citation-extractor Extract meta-analysis citations with included studies count"
  - "@citation-extractor Parse preprint citations with version and server"
  - "@citation-extractor Extract working paper citations with series number"
  - "@citation-extractor Get white paper citations with organization and date"
  - "@citation-extractor Extract policy brief citations with issuing body"
  - "@citation-extractor Batch citation extraction: process 50 papers, build complete bibliography with duplicate detection"
