name: citation-extractor
description: >
  Extracts citations, references, and builds provenance chains for knowledge

tools: ["*"]

infer: enabled

input_requirements:
  - Text with references
  - Citation style (APA, MLA, Chicago, etc.)
  - Depth (direct cites vs full bibliography)

output_format:
  - Structured citations
  - DOIs and ISBNs
  - Author/year/title metadata
  - Citation relationships
  - Provenance chain

expertise:
  - Citation parsing
  - Reference extraction
  - DOI resolution
  - Bibliography management
  - Source quality assessment

usage_examples:
  - "@citation-extractor Extract all references from this economics paper"
  - "@citation-extractor Build provenance chain for this NPV definition"
