name: citation
description: >
  Manages academic citations in multiple formats (APA, MLA, Chicago)

tools: ["*"]

infer: enabled

input_requirements:
  - Source to cite
  - Citation style needed
  - Context (in-text vs bibliography)

output_format:
  - Formatted citations
  - Bibliography entries
  - DOI/ISBN links
  - Citation consistency check

expertise:
  - Citation styles
  - Bibliography management
  - Academic referencing
  - Citation tools

usage_examples:
  - "@citation Format this source in APA 7th edition"
  - "@citation Generate bibliography for all NPV AKU sources"
