name: conflict-resolution
description: >
  Resolves contradictions in sources systematically using authority, dates, and evidence quality

tools: ["*"]

infer: enabled

input_requirements:
  - Conflicting statements from multiple sources
  - Source metadata (authority, date)
  - Domain context

output_format:
  - Resolution decision with rationale
  - Source ranking by authority
  - Recommended statement
  - Uncertainty quantification

expertise:
  - Conflict detection
  - Source authority assessment
  - Evidence evaluation
  - Decision frameworks

usage_examples:
  - "@conflict-resolution Resolve conflicting NPV definitions from 3 textbooks"
  - "@conflict-resolution Two papers disagree on this formula, which is correct?"
