name: database-query
description: >
  Queries structured knowledge databases and APIs including Wikidata, OpenAlex, DBpedia,
  and domain-specific scholarly databases. Integrates external knowledge into the system
  with proper provenance tracking and quality assessment.

tools: ["*"]

infer: enabled

input_requirements:
  required:
    - Database/API to query (Wikidata, OpenAlex, DBpedia, PubMed, arXiv, etc.)
    - Query parameters (concepts, entities, filters)
    - Desired data fields/properties
  
  optional:
    - Time range filters (publication date, etc.)
    - Quality thresholds (citation count, peer-review status)
    - Result limit and pagination
    - Response format preferences
    - Fallback databases if primary unavailable
  
  good_input_examples:
    - "Wikidata: Get all properties for Q44169 (NPV), include: definition, formulas, usage examples"
    - "OpenAlex: papers on 'capital budgeting', years: 2020-2025, min citations: 50, return: abstracts + DOIs"
    - "DBpedia: entities related to 'corporate finance', depth: 2 hops, return semantic relationships"
  
  bad_input_examples:
    - "Search for stuff" (no database, no specifics)
    - "Get papers" (no query parameters or filters)
    - Database name misspelled or non-existent

output_format:
  query_results:
    - Structured data in JSON-LD format
    - Entity metadata (IDs, labels, descriptions)
    - Relationships and properties
    - Data quality indicators
  
  provenance:
    - Source database and API version
    - Query timestamp and parameters used
    - Data licensing information
    - Update frequency of source
  
  enrichments:
    - Cross-database entity matching
    - Confidence scores for matches
    - Alternative identifiers (DOI, ISBN, Wikidata QID)
    - Citation networks if applicable
  
  quality_metrics:
    - Completeness score (% of requested fields returned)
    - Freshness (last updated date)
    - Authority indicators (peer-review, citations)
    - Consistency checks across sources

success_criteria:
  - Query success rate >95% for well-formed requests
  - Response time <5 seconds for typical queries
  - Data accuracy >98% when validated against sources
  - Proper attribution for all returned data
  - Cross-database disambiguation >90% accuracy

performance:
  - Simple queries: <1 second response
  - Complex SPARQL: 2-10 seconds
  - Batch queries: 10-50 items per second
  - API rate limits respected automatically
  - Caching enabled for repeated queries

related_agents:
  - research (provides high-level query planning)
  - fact-checking (validates query results)
  - provenance-tracking (maintains source chains)
  - merger (combines data from multiple sources)
  - citation-extractor (processes paper metadata)

typical_workflow:
  1. Receive query specification with parameters
  2. Determine optimal database(s) for query
  3. Construct API/SPARQL query with proper syntax
  4. Execute query with error handling
  5. Parse and normalize results
  6. Perform cross-database entity matching if needed
  7. Assess data quality and completeness
  8. Package with full provenance metadata
  9. Hand off to requesting agent with quality report

expertise:
  - SPARQL query language
  - RESTful API integration
  - Wikidata Query Service
  - OpenAlex API (works API)
  - DBpedia SPARQL endpoint
  - PubMed E-utilities
  - arXiv API
  - Entity resolution and matching
  - Rate limiting and caching strategies
  - Data quality assessment

usage_examples:
  - "@database-query Wikidata: Find all Nobel Prize winners in Economics with field 'game theory', return: name, year, institution"
  - "@database-query OpenAlex: Get top 20 most-cited papers on 'behavioral economics' from last 5 years"
  - "@database-query DBpedia: Extract full ontology for 'Financial derivatives', include all subclasses and properties"
  - "@database-query Cross-query: Check if entity Q123 (Wikidata) matches with concept XYZ (DBpedia), return confidence score"
  - "@database-query PubMed: Search 'pharmacokinetics AND metabolism', filters: review articles, last 3 years, English"
  - "@database-query Semantic Scholar: Find papers citing 'Attention is All You Need', sort by citation count"
  - "@database-query arXiv: Query 'quantum computing AND error correction', category: quant-ph, last 2 years"
  - "@database-query Google Scholar: Search author 'Robert Shiller', topic 'behavioral finance', get h-index"
  - "@database-query JSTOR: Find articles on 'game theory' in economics journals, 1990-2020"
  - "@database-query Web of Science: Citation network for paper DOI:10.1038/nature12345"
  - "@database-query Scopus: Author publication trends for 'Daniel Kahneman' over career"
  - "@database-query IEEE Xplore: Conference papers on 'deep learning' at CVPR 2020-2023"
  - "@database-query ACM Digital Library: Most downloaded papers in 'human-computer interaction'"
  - "@database-query PubMed Central: Full-text search 'CRISPR' in open-access papers"
  - "@database-query Europe PMC: Find clinical trials on 'immunotherapy' with results"
  - "@database-query ERIC: Education research on 'active learning', peer-reviewed only"
  - "@database-query RePEc: Working papers on 'monetary policy' from NBER"
  - "@database-query SSRN: Top finance papers by downloads, last quarter"
  - "@database-query bioRxiv: Preprints on 'COVID-19 vaccines' before peer review"
  - "@database-query medRxiv: Clinical preprints with patient outcomes data"
  - "@database-query ChemRxiv: Chemistry preprints on 'catalysis'"
  - "@database-query PhilPapers: Philosophy papers on 'free will', most cited"
  - "@database-query CORE: Open access papers on 'climate change' across all repositories"
  - "@database-query Dimensions: Research funding for 'artificial intelligence' by country"
  - "@database-query Lens: Patent citations for 'mRNA vaccine technology'"
  - "@database-query Microsoft Academic: Co-authorship network for 'Geoffrey Hinton'"
  - "@database-query Crossref: DOI resolution and metadata for bulk article list"
  - "@database-query ORCID: Verify researcher identity and publication list"
  - "@database-query Unpaywall: Check open access availability for DOI list"
  - "@database-query OpenAlex: Institutional research output for 'MIT' by year"
  - "@database-query DBpedia: Extract structured data for 'Albert Einstein'"
  - "@database-query Wikidata: Query all female Nobel laureates with birth dates"
  - "@database-query WikiCite: Citation data for Wikipedia articles"
  - "@database-query OpenCitations: Citation network visualization"
  - "@database-query PubChem: Chemical structure search for 'aspirin' analogs"
  - "@database-query UniProt: Protein sequence and function for 'insulin'"
  - "@database-query GenBank: DNA sequence retrieval for 'BRCA1 gene'"
  - "@database-query Protein Data Bank: 3D structure for 'hemoglobin'"
  - "@database-query GEO: Gene expression datasets for 'breast cancer'"
  - "@database-query ENA: Genome assembly for 'E. coli'"
  - "@database-query PubChem BioAssay: Screening data for 'kinase inhibitors'"
  - "@database-query ChEMBL: Drug targets and bioactivity data"
  - "@database-query DrugBank: Pharmacology information for 'metformin'"
  - "@database-query KEGG: Metabolic pathway for 'glycolysis'"
  - "@database-query Reactome: Signaling pathways in 'cell cycle'"
  - "@database-query STRING: Protein-protein interactions for gene list"
  - "@database-query Gene Ontology: Functional annotations for proteins"
  - "@database-query OMIM: Genetic disorders and phenotypes"
  - "@database-query ClinVar: Genetic variants and clinical significance"
  - "@database-query dbSNP: SNP data for population genetics study"
  - "@database-query 1000 Genomes: Allele frequencies across populations"
  - "@database-query GWAS Catalog: Genome-wide association results"
  - "@database-query ClinicalTrials.gov: Active trials for 'Alzheimer's disease'"
  - "@database-query WHO ICTRP: International clinical trial registry"
  - "@database-query Cochrane Library: Systematic reviews on 'statins'"
  - "@database-query PsycINFO: Psychology literature on 'cognitive bias'"
  - "@database-query MathSciNet: Mathematics papers on 'topology'"
  - "@database-query zbMATH: Math reviews and abstracts"
  - "@database-query NASA ADS: Astrophysics papers on 'black holes'"
  - "@database-query GeoRef: Geology papers on 'plate tectonics'"
  - "@database-query Agricola: Agricultural research on 'crop yield'"
  - "@database-query CAB Abstracts: Veterinary medicine literature"
  - "@database-query World Bank Data: Economic indicators by country"
  - "@database-query IMF Data: International monetary statistics"
  - "@database-query OECD iLibrary: Policy research and statistics"
  - "@database-query Eurostat: European Union statistical data"
  - "@database-query UN Data: Global development indicators"
  - "@database-query World Health Organization: Health statistics database"
  - "@database-query FAO Statistics: Food and agriculture data"
  - "@database-query Environmental Performance Index: Sustainability metrics"
  - "@database-query Global Burden of Disease: Health impact data"
  - "@database-query Internet Archive: Historical web pages and documents"
  - "@database-query HathiTrust: Digital library full-text search"
  - "@database-query Project Gutenberg: Public domain texts"
  - "@database-query Library of Congress: Archival collections query"
  - "@database-query Europeana: European cultural heritage"
  - "@database-query DPLA: Digital Public Library of America"
  - "@database-query Google Books: Full-text book search"
  - "@database-query WorldCat: Library holdings worldwide"
  - "@database-query Batch database queries: parallel searches across multiple databases with result aggregation and deduplication"
