name: database-query
description: >
  Queries structured knowledge databases like Wikidata, OpenAlex, and domain-specific DBs

tools: ["*"]

infer: enabled

input_requirements:
  - Database to query (Wikidata, OpenAlex, etc.)
  - Query parameters (concepts, filters)
  - Desired properties/fields

output_format:
  - Structured query results (JSON/RDF)
  - Entity relationships
  - Citations and provenance
  - Data quality scores

expertise:
  - SPARQL queries
  - Wikidata API
  - OpenAlex API
  - Database integration
  - Result aggregation

usage_examples:
  - "@database-query Get all Wikidata properties for 'Net Present Value'"
  - "@database-query Find OpenAlex papers on corporate finance from 2020-2025"
