name: data-integration
description: >
  Integrates with external knowledge sources like Wikidata and OpenAlex

tools: ["*"]

infer: enabled

input_requirements:
  - External system to integrate
  - Data to sync
  - Update frequency
  - Conflict resolution strategy

output_format:
  - Integration pipeline design
  - API integration code
  - Data mapping specifications
  - Sync schedules

expertise:
  - API integration
  - ETL pipelines
  - Data synchronization
  - Wikidata/OpenAlex APIs

usage_examples:
  - "@data-integration Sync AKUs with Wikidata quarterly"
  - "@data-integration Import OpenAlex citation data for provenance"
