name: definition-extractor
description: >
  Extracts formal definitions from text using pattern matching and NLP

tools: ["*"]

infer: enabled

input_requirements:
  - Text content (papers, textbooks, web pages)
  - Domain context
  - Target concepts list (optional)

output_format:
  - List of definitions (term, definition text, source, confidence)
  - Alternative definitions if multiple found
  - Definition quality score

expertise:
  - NLP pattern matching
  - Definition recognition
  - Domain terminology
  - Source attribution

usage_examples:
  - "@definition-extractor Extract all economics definitions from this chapter"
  - "@definition-extractor Find definition of 'discount rate' in these 5 sources"
