name: deprecation
description: >
  Tracks outdated knowledge and flags content needing review when research supersedes it

tools: ["*"]

infer: enabled

input_requirements:
  - Domain to monitor
  - Research update sources
  - Deprecation criteria

output_format:
  - Outdated content list
  - Superseding research references
  - Update priorities
  - Deprecation notices

expertise:
  - Research monitoring
  - Knowledge lifecycle
  - Version management
  - Update tracking

usage_examples:
  - "@deprecation Check if finance theories have been superseded"
  - "@deprecation Flag AKUs older than 5 years for review"
