name: devops
description: >
  Manages CI/CD pipelines, monitoring, and infrastructure

tools: ["*"]

infer: enabled

input_requirements:
  - System components
  - Deployment requirements
  - Monitoring needs
  - Performance targets

output_format:
  - CI/CD pipeline configuration
  - Monitoring dashboards
  - Infrastructure as code
  - Deployment procedures

expertise:
  - CI/CD
  - Infrastructure automation
  - Monitoring
  - Docker
  - GitHub Actions

usage_examples:
  - "@devops Set up automated testing for AKU validators"
  - "@devops Configure monitoring for rendering engine"
