name: example-generation
description: >
  Creates worked examples, case studies, and practice problems from concepts

tools: ["*"]

infer: enabled

input_requirements:
  - Concept to illustrate
  - Example type (simple, complex, real-world)
  - Difficulty level
  - Domain context

output_format:
  - Generated examples with solutions
  - Step-by-step explanations
  - Teaching notes
  - Practice variations

expertise:
  - Problem creation
  - Case study design
  - Solution writing
  - Difficulty calibration

usage_examples:
  - "@example-generation Create 5 NPV practice problems"
  - "@example-generation Generate real-world case study for equipment replacement"
