name: example-extractor
description: >
  Identifies and extracts worked examples, problem sets, and case studies from content

tools: ["*"]

infer: enabled

input_requirements:
  - Content source (textbook, paper, website)
  - Example type (worked problem, case study, scenario)
  - Domain context

output_format:
  - Extracted examples with problem statement
  - Step-by-step solutions
  - Teaching notes and explanation
  - Difficulty level assessment

expertise:
  - Example pattern recognition
  - Problem-solution pairing
  - Case study structure
  - Pedagogical content identification

usage_examples:
  - "@example-extractor Extract all worked examples from Chapter 8"
  - "@example-extractor Find NPV calculation examples in these sources"
