name: fact-checking
description: >
  Verifies accuracy of content against authoritative sources

tools: ["*"]

infer: enabled

input_requirements:
  - Content to verify (claims, facts, statistics)
  - Authoritative sources list
  - Domain context

output_format:
  - Verification results per claim
  - Source citations for verification
  - Confidence scores
  - Corrections if errors found

expertise:
  - Fact verification
  - Source evaluation
  - Statistical validation
  - Domain knowledge assessment

usage_examples:
  - "@fact-checking Verify all statistics in these economics AKUs"
  - "@fact-checking Check historical facts in this timeline"
