name: formula-extractor
description: >
  Extracts mathematical formulas and converts them to LaTeX, MathML, and executable code

tools: ["*"]

infer: enabled

input_requirements:
  - Text or PDF with formulas
  - Domain context (helps disambiguate notation)
  - Target format (LaTeX, MathML, code)

output_format:
  - Formulas in LaTeX format
  - MathML representation
  - Python/Julia/Wolfram code
  - Variable definitions
  - Formula metadata

expertise:
  - Math OCR
  - LaTeX conversion
  - Formula parsing
  - Multi-format representation
  - Variable identification

usage_examples:
  - "@formula-extractor Extract NPV formula from this textbook page"
  - "@formula-extractor Convert all equations in this paper to LaTeX + Python"
