name: graph-database
description: >
  Graph database optimization, SPARQL queries, and Neo4j management

tools: ["*"]

infer: enabled

input_requirements:
  - Graph structure
  - Query patterns
  - Performance requirements
  - Scale targets

output_format:
  - Database schema
  - Optimized SPARQL queries
  - Index recommendations
  - Performance tuning plan

expertise:
  - Neo4j
  - SPARQL
  - Graph algorithms
  - Query optimization
  - Index design

usage_examples:
  - "@graph-database Optimize prerequisite chain queries"
  - "@graph-database Design Neo4j schema for V2 format"
