name: implementation
description: >
  Assesses feasibility, creates phased implementation plans, manages execution

tools: ["*"]

infer: enabled

input_requirements:
  - Goals to achieve
  - Resource constraints
  - Timeline
  - Success criteria

output_format:
  - Implementation plan
  - Phase breakdown
  - Resource allocation
  - Risk mitigation
  - Success metrics

expertise:
  - Project planning
  - Phased execution
  - Feasibility analysis
  - Resource management

usage_examples:
  - "@implementation Create phased plan for NPV pilot"
  - "@implementation Assess feasibility of 100M AKU goal"
