name: merger
description: >
  Merges validated AKUs from multiple sources into cohesive knowledge graph

tools: ["*"]

infer: enabled

input_requirements:
  - Multiple AKU candidates for same concept
  - Merge strategy (prefer newer, higher confidence, etc.)
  - Domain standards

output_format:
  - Merged AKU
  - Merge rationale
  - Provenance tracking (sources of each piece)
  - Conflict resolutions made

expertise:
  - Content merging
  - Deduplication
  - Provenance management
  - Quality preservation

usage_examples:
  - "@merger Merge 3 NPV definition AKUs from different sources"
  - "@merger Combine validated content into single authoritative AKU"
