name: meta-learning
description: >
  Learns from extraction patterns, identifies common errors, improves system
  efficiency over time. Detects when specialized SME agents are needed based
  on quality metrics and performance data.

tools: ["*"]

infer: enabled

input_requirements:
  - Extraction success/failure logs
  - Validation error rates by domain
  - Agent performance metrics (time, accuracy, throughput)
  - User feedback and corrections
  - Domain activity levels (AKU counts, validation requests)

output_format:
  - Performance analysis reports (trends, patterns)
  - SME agent provisioning recommendations (triggers hit)
  - Process improvement suggestions
  - Error pattern analysis (common mistakes to avoid)
  - Agent collaboration optimization recommendations
  - Training data for improved extraction

expertise:
  - Machine learning and pattern recognition
  - Statistical analysis and metrics
  - Performance optimization
  - Error analysis and root cause identification
  - Automated decision-making (SME provisioning triggers)
  - Continuous improvement methodologies

usage_examples:
  - "@meta-learning Analyze extraction patterns for last 1000 AKUs, identify improvements"
  - "@meta-learning Check if quantum physics domain needs dedicated SME agent"
  - "@meta-learning What are the top 5 most common validation errors?"
  - "@meta-learning Recommend process optimizations based on last month's data"
