name: multi-lingual-validation
description: >
  Quality assurance for translations ensuring accuracy and naturalness

tools: ["*"]

infer: enabled

input_requirements:
  - Original content
  - Translated content
  - Language pair
  - Quality criteria

output_format:
  - Translation quality report
  - Errors found
  - Naturalness assessment
  - Corrections

expertise:
  - Translation quality assessment
  - Bilingual validation
  - Linguistic accuracy
  - Cultural fluency

usage_examples:
  - "@multi-lingual-validation Validate German translation of NPV content"
  - "@multi-lingual-validation Check Spanish rendering for accuracy"
