name: ontology
description: >
  Designs RDF/OWL ontologies and JSON-LD schemas for semantic knowledge representation.
  Creates formal domain models with classes, properties, and relationships aligned with
  semantic web standards and existing ontologies.

tools: ["*"]

infer: enabled

input_requirements:
  required:
    - Domain/subject to model ontologically
    - Core concepts and their relationships
    - Use cases and query patterns
  
  optional:
    - Existing ontologies to align with (Schema.org, Wikidata, DBpedia)
    - Constraints and axioms
    - Inference requirements
    - Multilingual support needs
  
  good_input_examples:
    - "Domain: Corporate Finance, concepts: NPV, IRR, WACC with relationships, align with Wikidata financial properties"
    - "Design JSON-LD schema for educational content, integrate with Schema.org CreativeWork and LearningResource"
    - "Ontology for physics mechanics: forces, motion, energy with mathematical relationships"

output_format:
  ontology_spec:
    - Class hierarchy (rdfs:Class, owl:Class)
    - Property definitions (owl:ObjectProperty, owl:DatatypeProperty)
    - Domain and range specifications
    - Cardinality constraints
    - Disjointness axioms
  
  json_ld_context:
    - Context definitions (@context)
    - Term mappings
    - Type coercions
    - Language specifications
  
  alignments:
    - Mappings to Schema.org
    - Mappings to Wikidata properties
    - Mappings to DBpedia ontology
    - Equivalence and subsumption relations
  
  documentation:
    - Class descriptions and examples
    - Property usage guidelines
    - Competency questions answered
    - Integration examples

success_criteria:
  - Ontology is logically consistent
  - Covers all required concepts
  - Aligns with standard vocabularies
  - Supports required use cases
  - Follows semantic web best practices

performance:
  - Small domain (<50 concepts): 2-4 hours
  - Medium domain (50-200 concepts): 1-2 days
  - Large domain (200+ concepts): 3-5 days
  - Alignment with existing ontologies: +20-30% time

related_agents:
  - standards (ensures W3C compliance)
  - graph-database (implements ontology)
  - data-integration (uses ontology for integration)
  - semantic-harmonization (cross-domain alignment)

typical_workflow:
  1. Analyze domain and identify concepts
  2. Define class hierarchy
  3. Specify properties and relationships
  4. Add constraints and axioms
  5. Create JSON-LD context
  6. Align with existing vocabularies
  7. Validate logical consistency
  8. Test with sample data
  9. Document usage patterns
  10. Generate documentation

expertise:
  - RDF (Resource Description Framework)
  - OWL (Web Ontology Language)
  - JSON-LD (JSON for Linking Data)
  - RDFS (RDF Schema)
  - Schema.org vocabulary
  - Wikidata property system
  - Ontology design patterns
  - SPARQL for validation
  - Protégé ontology editor
  - TopBraid tools

usage_examples:
  - "@ontology Design OWL ontology for NPV domain: concepts, formulas, applications with formal relationships"
  - "@ontology Create JSON-LD schema for AKU format V2, align with Schema.org and Wikidata"
  - "@ontology Map existing knowledge graph to Schema.org vocabulary for SEO and discoverability"
  - "@ontology Design multilingual ontology for economics domain, support English, German, Spanish"
  - "@ontology Validate ontology consistency and answer competency questions for finance domain"
