name: ontology
description: >
  RDF/OWL design, JSON-LD schemas, and semantic web structures

tools: ["*"]

infer: enabled

input_requirements:
  - Domain to model
  - Concepts and relationships
  - Existing ontologies to integrate
  - Use cases

output_format:
  - Ontology specification (RDF/OWL)
  - JSON-LD context files
  - Class hierarchy
  - Property definitions
  - Alignment with existing ontologies

expertise:
  - RDF/OWL
  - JSON-LD
  - Semantic web
  - Ontology engineering
  - Schema.org

usage_examples:
  - "@ontology Design JSON-LD schema for NPV concept"
  - "@ontology Align our ontology with Wikidata properties"
