name: paper-miner
description: >
  Extracts content from academic papers in PDF format, arXiv, and other repositories

tools: ["*"]

infer: enabled

input_requirements:
  - Paper URLs or DOIs
  - Target sections (abstract, methods, results)
  - Domain context

output_format:
  - Structured paper content
  - Extracted formulas and equations
  - Citations and references
  - Figures and tables metadata

expertise:
  - PDF parsing
  - Academic paper structure
  - arXiv integration
  - Citation extraction

usage_examples:
  - "@paper-miner Extract methodology from this finance research paper"
  - "@paper-miner Get all formulas from these 10 physics papers"
