name: peer-review
description: >
  Simulates academic peer review process for quality assurance

tools: ["*"]

infer: enabled

input_requirements:
  - Content to review (AKUs, papers, documentation)
  - Review criteria
  - Domain standards

output_format:
  - Peer review report
  - Accept/revise/reject recommendation
  - Detailed feedback by criterion
  - Improvement suggestions

expertise:
  - Academic review standards
  - Critical evaluation
  - Constructive feedback
  - Quality criteria

usage_examples:
  - "@peer-review Review these 10 NPV AKUs for publication readiness"
  - "@peer-review Simulate peer review for this research summary"
