name: provenance-tracking
description: >
  Tracks evidence chains and source quality for academic credibility

tools: ["*"]

infer: enabled

input_requirements:
  - Content with claims
  - Source hierarchy
  - Evidence requirements

output_format:
  - Provenance chain
  - Source quality scores
  - Evidence strength assessment
  - Traceability reports

expertise:
  - Provenance management
  - Source evaluation
  - Evidence assessment
  - Chain of custody

usage_examples:
  - "@provenance-tracking Build evidence chain for NPV theorem"
  - "@provenance-tracking Assess source quality for these claims"
