name: quality
description: >
  Overall quality assurance including metrics, standards compliance, and continuous improvement

tools: ["*"]

infer: enabled

input_requirements:
  - Content to assess
  - Quality criteria
  - Standards to check (V2 format, accessibility, etc.)

output_format:
  - Quality score
  - Standards compliance report
  - Quality metrics
  - Improvement areas ranked
  - Pass/fail status

expertise:
  - Quality metrics
  - Standards compliance
  - Process improvement
  - Quality frameworks

usage_examples:
  - "@quality Assess overall quality of finance subdomain AKUs"
  - "@quality Check compliance with V2 format specification"
