name: relationship-extractor
description: >
  Identifies connections, prerequisites, and relationships between concepts

tools: ["*"]

infer: enabled

input_requirements:
  - Content describing concepts
  - Concept list
  - Relationship types to identify (prerequisite, enables, related, etc.)

output_format:
  - Concept relationships graph
  - Prerequisite chains
  - Related concepts
  - Relationship confidence scores
  - Context for each relationship

expertise:
  - Relationship identification
  - Dependency analysis
  - Semantic relationships
  - Graph construction
  - Prerequisite ordering

usage_examples:
  - "@relationship-extractor Find all prerequisites for understanding NPV"
  - "@relationship-extractor Map relationships between finance concepts in this chapter"
