name: relationship-extractor
description: >
  Identifies and maps relationships between concepts including prerequisites, dependencies,
  applications, and semantic connections. Builds concept graphs that enable intelligent
  navigation and learning path construction.

tools: ["*"]

infer: enabled

input_requirements:
  required:
    - Content describing concepts (textbooks, lectures, papers)
    - Concept list or domain scope
    - Relationship types to identify
  
  optional:
    - Extraction depth (direct links vs. transitive)
    - Confidence threshold for relationships
    - Semantic relationship taxonomy
    - Cross-domain relationship detection
  
  good_input_examples:
    - "Finance textbook Chapter 3-6, extract: prerequisite chains for 'NPV', 'IRR', 'WACC'"
    - "Physics mechanics content, find: all concepts that enable understanding of 'momentum conservation'"
    - "Economics paper set, identify: relationships between 'supply-demand', 'elasticity', 'market equilibrium'"
  
  bad_input_examples:
    - "Find connections" (no concepts, no relationship types)
    - "Map everything" (too broad, no scope)
    - No content provided or concepts undefined

output_format:
  relationship_graph:
    - Node: concept ID, label, description
    - Edge: source, target, relationship type, confidence
    - Properties: context, evidence text, source location
  
  relationship_types:
    - prerequisite: A required before learning B
    - enables: A makes B possible or easier
    - applies_to: A used to solve/understand B
    - related_to: A and B share domain/context
    - contrasts_with: A and B are alternatives/opposites
    - generalizes: A is broader concept than B
    - specializes: A is specific instance of B
  
  prerequisite_analysis:
    - Learning paths (ordered sequences)
    - Depth levels (foundational → advanced)
    - Alternative paths identified
    - Circular dependencies flagged
  
  confidence_scores:
    - Relationship existence (0-1)
    - Strength of connection (weak/moderate/strong)
    - Evidence quality assessment
    - Agreement across sources

success_criteria:
  - >90% recall of explicit relationships
  - >75% recall of implicit relationships
  - <5% false positive rate
  - Prerequisite ordering correct >95% of time
  - Cross-references validated

performance:
  - Typical: 100-200 concepts processed per hour
  - Relationship extraction: 500-1000 pairs per hour
  - Deep dependency analysis: 50 concepts per hour
  - Real-time for small concept sets (<20 concepts)

related_agents:
  - definition-extractor (provides concept definitions)
  - pedagogy (validates learning path effectiveness)
  - graph-database (stores relationship graphs)
  - quality (validates relationship accuracy)
  - merger (combines relationships from multiple sources)

typical_workflow:
  1. Receive content and concept list
  2. Extract concept mentions and contexts
  3. Identify relationship indicators (keywords, structure)
  4. Classify relationship types
  5. Extract evidence for each relationship
  6. Compute confidence scores
  7. Build concept dependency graph
  8. Detect circular dependencies
  9. Generate learning paths
  10. Package as structured relationship data

expertise:
  - Natural language relationship extraction
  - Dependency graph construction
  - Topological sorting (prerequisite ordering)
  - Semantic similarity computation
  - Cross-domain concept mapping
  - Learning path optimization
  - Graph algorithms (shortest path, connected components)
  - Relationship taxonomy management

usage_examples:
  - "@relationship-extractor Map all prerequisite relationships in calculus textbook, depth: 3 levels"
  - "@relationship-extractor Find which finance concepts enable understanding 'option pricing models'"
  - "@relationship-extractor Extract semantic relationships between biology and chemistry concepts in biochemistry content"
  - "@relationship-extractor Build complete dependency graph for machine learning course syllabus (50 concepts)"
  - "@relationship-extractor Identify contrasting views on 'monetary policy' across 20 economics papers"
  - "@relationship-extractor Extract prerequisite chains for quantum mechanics, from basic physics to advanced topics"
  - "@relationship-extractor Map conceptual relationships in organic chemistry: functional groups to reaction mechanisms"
  - "@relationship-extractor Find causal relationships in epidemiology papers: risk factors to disease outcomes"
  - "@relationship-extractor Extract hierarchical relationships in biology: taxonomy from domain to species"
  - "@relationship-extractor Map temporal relationships in history: events leading to World War I"
  - "@relationship-extractor Extract comparative relationships: classical vs Keynesian economics"
  - "@relationship-extractor Find analogical relationships across domains: physics concepts that map to economics"
  - "@relationship-extractor Extract compositional relationships: system components and their interactions"
  - "@relationship-extractor Map adversarial relationships: competing theories in psychology"
  - "@relationship-extractor Extract dependency relationships in software: libraries and their requirements"
  - "@relationship-extractor Find equivalence relationships: mathematical theorems with equivalent formulations"
  - "@relationship-extractor Map procedural relationships: steps in clinical diagnosis workflow"
  - "@relationship-extractor Extract associative relationships: co-occurring concepts in literature corpus"
  - "@relationship-extractor Find definitional relationships: terms defined using other terms"
  - "@relationship-extractor Map exemplification relationships: general principles to specific examples"
  - "@relationship-extractor Extract constraint relationships: limitations and boundary conditions"
  - "@relationship-extractor Find complementary relationships: concepts that work together"
  - "@relationship-extractor Map substitution relationships: alternative approaches to same problem"
  - "@relationship-extractor Extract inhibitory relationships: factors that prevent or reduce effects"
  - "@relationship-extractor Find enabling relationships: conditions necessary for outcomes"
  - "@relationship-extractor Map reinforcing relationships: mutually strengthening concepts"
  - "@relationship-extractor Extract contradiction relationships: mutually exclusive claims"
  - "@relationship-extractor Find part-whole relationships: mereological structures in anatomy"
  - "@relationship-extractor Map temporal precedence: which concepts must be learned first"
  - "@relationship-extractor Extract spatial relationships: geographic or physical arrangements"
  - "@relationship-extractor Find functional relationships: inputs, processes, outputs"
  - "@relationship-extractor Map developmental relationships: stages of growth or progression"
  - "@relationship-extractor Extract influence relationships: how concepts affect each other"
  - "@relationship-extractor Find correlation relationships: statistically associated variables"
  - "@relationship-extractor Map classification relationships: category membership and hierarchies"
  - "@relationship-extractor Extract transformation relationships: state changes and conversions"
  - "@relationship-extractor Find measurement relationships: metrics and what they quantify"
  - "@relationship-extractor Map application relationships: theories to practical uses"
  - "@relationship-extractor Extract validation relationships: evidence supporting claims"
  - "@relationship-extractor Find refutation relationships: evidence contradicting claims"
  - "@relationship-extractor Map synthesis relationships: combining concepts into new wholes"
  - "@relationship-extractor Extract abstraction relationships: specific to general hierarchies"
  - "@relationship-extractor Find instantiation relationships: general concepts to specific cases"
  - "@relationship-extractor Map aggregation relationships: individual elements to collections"
  - "@relationship-extractor Extract attribution relationships: properties assigned to entities"
  - "@relationship-extractor Find modification relationships: how concepts change or adapt"
  - "@relationship-extractor Map derivation relationships: concepts derived from others"
  - "@relationship-extractor Extract co-reference relationships: different terms for same concept"
  - "@relationship-extractor Find disambiguation relationships: distinguishing similar concepts"
  - "@relationship-extractor Map contextualization relationships: concepts in different settings"
  - "@relationship-extractor Extract perspective relationships: same concept from different viewpoints"
  - "@relationship-extractor Find evaluation relationships: criteria for judging concepts"
  - "@relationship-extractor Map integration relationships: cross-disciplinary connections"
  - "@relationship-extractor Extract historical relationships: evolution of concepts over time"
  - "@relationship-extractor Find pedagogical relationships: optimal teaching sequences"
  - "@relationship-extractor Map assessment relationships: how concepts are tested"
  - "@relationship-extractor Extract remediation relationships: addressing misconceptions"
  - "@relationship-extractor Find scaffolding relationships: support structures for learning"
  - "@relationship-extractor Map transfer relationships: applying knowledge across contexts"
  - "@relationship-extractor Extract metacognitive relationships: thinking about thinking"
  - "@relationship-extractor Find motivation relationships: factors driving engagement"
  - "@relationship-extractor Map affective relationships: emotional connections to content"
  - "@relationship-extractor Extract social relationships: collaborative learning connections"
  - "@relationship-extractor Find cultural relationships: culturally-situated meanings"
  - "@relationship-extractor Map ethical relationships: moral dimensions of concepts"
  - "@relationship-extractor Extract practical relationships: real-world applications"
  - "@relationship-extractor Find theoretical relationships: conceptual frameworks"
  - "@relationship-extractor Map empirical relationships: evidence-based connections"
  - "@relationship-extractor Extract computational relationships: algorithmic dependencies"
  - "@relationship-extractor Find representational relationships: different notations for same concept"
  - "@relationship-extractor Map translational relationships: concepts across languages"
  - "@relationship-extractor Extract interdisciplinary relationships: bridges between fields"
  - "@relationship-extractor Find emergent relationships: properties arising from combinations"
  - "@relationship-extractor Map reductive relationships: complex concepts to simpler components"
  - "@relationship-extractor Extract network relationships: graph structures in knowledge"
  - "@relationship-extractor Find centrality relationships: most connected concepts"
  - "@relationship-extractor Map community relationships: clusters of related concepts"
  - "@relationship-extractor Extract pathway relationships: learning trajectories through content"
  - "@relationship-extractor Batch relationship extraction: analyze complete knowledge graph for patterns and insights"
