name: rendering
description: >
  Transforms AKUs to human-readable multi-format outputs (markdown, PDF, HTML, LaTeX)

tools: ["*"]

infer: enabled

input_requirements:
  - AKUs to render
  - Target audience
  - Output format
  - Language
  - Style preferences

output_format:
  - Rendered content in requested format
  - Appropriate examples for audience
  - Glossary if needed
  - Metadata

expertise:
  - Content transformation
  - Multi-format publishing
  - Audience adaptation
  - Style formatting

usage_examples:
  - "@rendering Transform NPV AKUs to German elementary school markdown"
  - "@rendering Create PDF textbook chapter from finance AKUs"
