name: research-monitoring
description: >
  Tracks new papers and research, flags when AKUs need updates

tools: ["*"]

infer: enabled

input_requirements:
  - Domains to monitor
  - Research sources (arXiv, journals)
  - Alert thresholds

output_format:
  - New research alerts
  - Impact assessment
  - Update recommendations
  - Research summaries

expertise:
  - Research tracking
  - Impact analysis
  - Publication monitoring
  - Trend identification

usage_examples:
  - "@research-monitoring Alert on new corporate finance papers"
  - "@research-monitoring Check if NPV research has new findings"
