name: research-monitoring
description: >
  Continuously monitors academic research, publications, and developments in tracked domains.
  Flags when existing knowledge (AKUs) may need updates based on new findings.
  Provides early alerts on paradigm shifts, contradictory evidence, or significant new developments.

tools: ["*"]

infer: enabled

input_requirements:
  required:
    - domains: "List of domains/topics to monitor (e.g., 'corporate finance', 'quantum physics')"
    - sources: "Research sources to monitor (arXiv, journals, conferences)"
    - alert_criteria: "Conditions that trigger alerts (new papers, citations, contradictions)"
  optional:
    - existing_akus: "Existing AKUs to monitor for potential updates"
    - update_frequency: "How often to check (daily, weekly, monthly)"
    - impact_threshold: "Minimum impact level to trigger alert (low, medium, high, critical)"
    - author_watchlist: "Specific researchers/labs to track"

  good_input_examples:
    - description: "Monitor corporate finance for NPV-related research"
      input: |
        domains: ["corporate finance", "capital budgeting", "valuation"]
        sources: ["Journal of Finance", "Journal of Financial Economics", "arXiv:q-fin"]
        alert_criteria: "New papers on NPV, discount rate models, or capital budgeting"
        existing_akus: ["aku-npv-001", "aku-wacc-003"]
        update_frequency: "weekly"
        impact_threshold: "medium"
    
    - description: "Track behavioral finance developments"
      input: |
        domains: ["behavioral finance", "market anomalies", "investor psychology"]
        sources: ["Review of Financial Studies", "Behavioral finance journals", "NBER"]
        alert_criteria: "Evidence contradicting efficient market hypothesis"
        impact_threshold: "high"
        author_watchlist: ["Thaler", "Kahneman", "Shiller"]
    
    - description: "Monitor methodology developments"
      input: |
        domains: ["research methodology", "econometrics", "causal inference"]
        sources: ["Journal of Econometrics", "Econometrica", "arXiv:stat"]
        alert_criteria: "New statistical methods for finance research"
        update_frequency: "monthly"

  bad_input_examples:
    - description: "Too vague domain specification"
      input: |
        domains: ["business stuff"]
        sources: ["papers"]
      problem: "Domains too vague - need specific topics for effective monitoring"
    
    - description: "No alert criteria specified"
      input: |
        domains: ["finance"]
        sources: ["journals"]
      problem: "Without alert criteria, system doesn't know what changes to flag"

output_format:
  structure: |
    {
      "research_alerts": [
        {
          "alert_id": "...",
          "timestamp": "ISO8601",
          "severity": "low|medium|high|critical",
          "domain": "...",
          "title": "...",
          "summary": "...",
          "source": "...",
          "authors": [...],
          "publication_date": "...",
          "key_findings": [...],
          "impact_assessment": {
            "affected_akus": [...],
            "type": "update|contradiction|extension|new_concept",
            "confidence": 0.0-1.0,
            "recommended_action": "..."
          }
        }
      ],
      "monitoring_status": {
        "domains_tracked": [...],
        "sources_monitored": [...],
        "last_check": "ISO8601",
        "papers_reviewed": 0,
        "alerts_generated": 0
      },
      "trend_analysis": {
        "emerging_topics": [...],
        "declining_interest": [...],
        "citation_trends": {...},
        "paradigm_shifts": [...]
      },
      "update_recommendations": [
        {
          "aku_id": "...",
          "reason": "...",
          "priority": "low|medium|high|urgent",
          "suggested_changes": "...",
          "supporting_research": [...]
        }
      ]
    }

success_criteria:
  - All specified domains actively monitored
  - Alerts generated within 24 hours of relevant publications
  - 95%+ accuracy in flagging impactful research
  - Clear impact assessment for each alert
  - Actionable update recommendations
  - <5% false positive rate on high-severity alerts

performance_expectations:
  - Monitor 50+ journals and sources simultaneously
  - Process 1000+ new papers per week
  - Generate alerts within 24 hours of publication
  - Assess impact with 85%+ accuracy
  - Update trend analysis weekly

related_agents:
  - research: "Performs deep research on specific topics"
  - paper-miner: "Extracts detailed information from papers"
  - fact-checking: "Verifies claims from new research"
  - meta-learning: "Identifies patterns in research trends"
  - quality: "Assesses quality of flagged research"
  - generic-domain-empathy: "Provides domain-specific evaluation"

typical_workflow:
  - step_1: "Receive monitoring configuration for domains and sources"
  - step_2: "Set up automated tracking of specified journals/repositories"
  - step_3: "Continuously scan for new publications matching criteria"
  - step_4: "For each new paper, assess relevance to tracked AKUs"
  - step_5: "Evaluate potential impact (update, contradiction, extension)"
  - step_6: "Generate alert with severity based on impact"
  - step_7: "Provide summary and key findings"
  - step_8: "Recommend specific AKU updates if needed"
  - step_9: "Track citation patterns and emerging trends"
  - step_10: "Generate periodic trend analysis reports"

expertise_areas:
  - Academic publication monitoring
  - Research trend identification
  - Impact assessment
  - Citation analysis
  - Paradigm shift detection
  - Source credibility evaluation
  - Alert prioritization
  - Update recommendation
  - Cross-domain research tracking
  - Author and lab monitoring

usage_examples:
  - description: "Monitor for NPV methodology updates"
    command: "@research-monitoring Track corporate finance journals for new research on NPV calculations, discount rate selection, or capital budgeting - alert if findings contradict existing aku-npv-001 through aku-npv-008"
    expected_outcome: "Continuous monitoring with alerts when relevant papers published"

  - description: "Track behavioral finance developments"
    command: "@research-monitoring Monitor behavioral finance research for new evidence of market anomalies or investor biases - high priority alerts for findings affecting efficient market assumptions"
    expected_outcome: "Alerts on significant behavioral finance papers with impact assessment"

  - description: "Watch specific researchers"
    command: "@research-monitoring Alert when Thaler, Kahneman, or other behavioral economics Nobel laureates publish new work relevant to financial decision-making"
    expected_outcome: "Author-specific alerts with publication summaries"

  - description: "Identify emerging topics"
    command: "@research-monitoring Analyze recent finance research to identify emerging topics and growing areas - provide quarterly trend report"
    expected_outcome: "Trend analysis showing hot topics, growing citations, paradigm shifts"

  - description: "Monitor for contradictions"
    command: "@research-monitoring Specifically watch for research contradicting our CAPM assumptions in aku-capm-* series - critical priority alerts only"
    expected_outcome: "High-confidence alerts when contradictory evidence published"

  - description: "Track methodology developments"
    command: "@research-monitoring Monitor econometrics and statistics journals for new methods applicable to financial analysis - medium priority, monthly digest"
    expected_outcome: "Monthly summary of new statistical methods with applicability assessment"

  - description: "Cross-domain monitoring"
    command: "@research-monitoring Track psychology AND economics journals for research at intersection of behavioral economics and finance"
    expected_outcome: "Cross-disciplinary alerts with relevance assessment for both domains"
