name: software-architecture
description: >
  System design, APIs, microservices, and scalability planning

tools: ["*"]

infer: enabled

input_requirements:
  - System requirements
  - Scale targets
  - Integration needs
  - Performance criteria

output_format:
  - Architecture diagrams
  - API specifications
  - Service design documents
  - Scalability plan
  - Technology recommendations

expertise:
  - Distributed systems
  - API design
  - Microservices
  - Scalability
  - System integration

usage_examples:
  - "@software-architecture Design rendering engine microservice"
  - "@software-architecture Plan architecture for 100M AKU scale"
