name: textbook-parser
description: >
  Extracts structured content from textbooks using OCR and intelligent parsing

tools: ["*"]

infer: enabled

input_requirements:
  - Textbook PDF or images
  - Chapter/section to extract
  - Target concept list

output_format:
  - Structured textbook content (chapters, sections, subsections)
  - Extracted definitions and theorems
  - Practice problems and solutions
  - Figures and diagrams

expertise:
  - OCR (Optical Character Recognition)
  - Textbook structure recognition
  - Math formula recognition
  - Problem-solution pairing

usage_examples:
  - "@textbook-parser Extract Chapter 5 from Brealey & Myers Corporate Finance"
  - "@textbook-parser Parse practice problems from this algebra textbook"
