name: textbook-parser
description: >
  Extracts and structures educational content from textbooks using intelligent parsing,
  OCR, and semantic analysis. Processes PDF/image textbooks to create AKU-ready content
  with preserved structure, formulas, and pedagogical elements.

tools: ["*"]

infer: enabled

input_requirements:
  required:
    - Textbook file (PDF, images, or ePub)
    - Target chapters/sections to extract
    - Subject domain classification
  
  optional:
    - Specific concepts to focus on
    - Extraction depth (overview, standard, comprehensive)
    - Figure extraction requirements
    - Citation style preferences
  
  good_input_examples:
    - "PDF: Mankiw_Macroeconomics_10e.pdf, Chapter 3 (National Income), domain: economics"
    - "Images: physics_mechanics_ch5/*.png, section: Newton's Laws, depth: comprehensive"
    - "Extract all worked examples from Calculus textbook Chapter 7 on integration techniques"
  
  bad_input_examples:
    - "Parse this book" (no file, no specifics)
    - "Get the math stuff" (vague, no structure guidance)
    - Handwritten notes without OCR preprocessing

output_format:
  structured_content:
    - Hierarchical outline (chapters → sections → subsections → paragraphs)
    - Section metadata (page numbers, learning objectives, prerequisites)
    - Cross-references and dependencies mapped
  
  extracted_elements:
    - Definitions with context and examples
    - Theorems/laws with proofs and applications
    - Formulas in LaTeX and plain text
    - Worked examples with step-by-step solutions
    - Practice problems with difficulty ratings
    - Tables, figures, diagrams with captions
  
  format:
    - JSON-LD for semantic structure
    - Separate files per chapter/section
    - Image files extracted and referenced
    - Metadata includes: source citation, page ranges, extraction timestamp
  
  quality_indicators:
    - OCR confidence scores per paragraph
    - Formula recognition accuracy
    - Structure completeness percentage

success_criteria:
  - >90% OCR accuracy on printed text
  - >85% formula recognition success
  - Preserved pedagogical structure (examples, exercises, summaries)
  - All figures extracted with readable resolution
  - Cross-references maintained

performance:
  - Typical: 30-50 pages per minute for standard textbooks
  - Math-heavy: 10-20 pages per minute (formula processing)
  - Image-only: 5-10 pages per minute (OCR overhead)
  - Parallel processing supported for multi-chapter extraction

related_agents:
  - definition-extractor (refines extracted definitions)
  - formula-extractor (validates math expressions)
  - example-extractor (structures worked examples)
  - citation-extractor (processes bibliography)
  - figure-analyzer (interprets diagrams)
  - quality (validates extraction completeness)

typical_workflow:
  1. Receive textbook file and extraction parameters
  2. Perform OCR if needed (image-based PDFs)
  3. Identify structural elements (chapters, sections, headings)
  4. Extract text, formulas, figures separately
  5. Parse definitions, theorems, examples
  6. Map cross-references and dependencies
  7. Package as structured JSON-LD output
  8. Hand off to extractors for AKU creation

expertise:
  - OCR engines (Tesseract, ABBYY, mathpix)
  - PDF structure analysis
  - Mathematical notation recognition (LaTeX, MathML)
  - Textbook layout patterns
  - Pedagogical element identification
  - Image preprocessing and enhancement
  - Multi-column and complex layout handling

usage_examples:
  - "@textbook-parser Extract Chapters 1-3 from Brealey_Corporate_Finance_13e.pdf, domain: finance, depth: comprehensive"
  - "@textbook-parser Parse all calculus problems from Stewart_Calculus_9e.pdf Chapter 4, include solutions"
  - "@textbook-parser Process Tipler_Physics_6e.pdf Section 5.3 (Work and Energy), extract all worked examples and figures"
  - "@textbook-parser Quick overview extraction from Samuelson_Economics.pdf Chapter 10, definitions and key formulas only"
  - "@textbook-parser Batch process folder economics_textbooks/*.pdf, extract all supply-demand related content"
  - "@textbook-parser Extract problem sets: Mankiw_Principles_Economics.pdf, all end-of-chapter exercises with solutions"
  - "@textbook-parser Parse medical textbook: Gray's Anatomy, extract cardiovascular system diagrams and descriptions"
  - "@textbook-parser Multi-chapter extraction: Organic Chemistry Wade, Chapters 5-8, all reaction mechanisms"
  - "@textbook-parser Selective parsing: extract only formulas and definitions from Mathematical Methods textbook"
  - "@textbook-parser Cross-reference extraction: find all references to NPV across multiple finance textbooks"
  - "@textbook-parser Table extraction: pull all data tables from Statistics textbook for analysis"
  - "@textbook-parser Figure extraction: high-quality images of diagrams from Engineering Mechanics textbook"
  - "@textbook-parser Index-based extraction: use textbook index to locate all mentions of specific concepts"
  - "@textbook-parser Multilingual parsing: extract from German economics textbook, translate key concepts"
  - "@textbook-parser Historical textbook: parse Adam Smith's Wealth of Nations, modernize language and notation"
  - "@textbook-parser Equation extraction: LaTeX conversion of all mathematical expressions from textbook"
  - "@textbook-parser Case study extraction: business textbook case studies with analysis questions"
  - "@textbook-parser Code snippet extraction: programming textbook examples with explanations"
  - "@textbook-parser Citation extraction: build bibliography from all textbook references"
  - "@textbook-parser Glossary extraction: compile terminology from multiple textbook glossaries"
  - "@textbook-parser Chapter summary extraction: executive summaries from each chapter"
  - "@textbook-parser Learning objectives extraction: pull stated learning goals from each section"
  - "@textbook-parser Worked example extraction: step-by-step solutions from physics textbook"
  - "@textbook-parser Practice problem extraction: unsolved problems for student practice"
  - "@textbook-parser Answer key extraction: solutions manual parsing and validation"
  - "@textbook-parser Review question extraction: end-of-chapter review materials"
  - "@textbook-parser Concept map extraction: visual representations of knowledge structure"
  - "@textbook-parser Timeline extraction: historical sequences from history textbooks"
  - "@textbook-parser Biography extraction: scientist profiles from science textbooks"
  - "@textbook-parser Experimental procedure extraction: lab manual protocols and safety notes"
  - "@textbook-parser Legal case extraction: law textbook case summaries and holdings"
  - "@textbook-parser Theorem extraction: formal mathematical theorems with proofs"
  - "@textbook-parser Algorithm extraction: pseudocode and complexity analysis from CS textbooks"
  - "@textbook-parser Data structure extraction: implementation details and usage examples"
  - "@textbook-parser Design pattern extraction: software patterns from engineering textbooks"
  - "@textbook-parser Clinical guideline extraction: medical textbook treatment protocols"
  - "@textbook-parser Chemical reaction extraction: organic chemistry synthesis pathways"
  - "@textbook-parser Biological pathway extraction: metabolic and signaling pathways"
  - "@textbook-parser Anatomical structure extraction: detailed descriptions and relationships"
  - "@textbook-parser Pharmacology extraction: drug mechanisms, interactions, dosing"
  - "@textbook-parser Psychology study extraction: experimental designs and findings"
  - "@textbook-parser Sociological theory extraction: major theoretical frameworks"
  - "@textbook-parser Philosophical argument extraction: logical structure and objections"
  - "@textbook-parser Literary analysis extraction: themes, symbols, critical perspectives"
  - "@textbook-parser Art history extraction: period styles, techniques, major works"
  - "@textbook-parser Music theory extraction: notation, harmony, composition techniques"
  - "@textbook-parser Language grammar extraction: syntax rules, examples, exceptions"
  - "@textbook-parser Cultural context extraction: social customs, historical background"
  - "@textbook-parser Geographic information extraction: maps, climate data, demographics"
  - "@textbook-parser Economic model extraction: supply-demand, game theory, market structures"
  - "@textbook-parser Political theory extraction: governance systems, ideologies, institutions"
  - "@textbook-parser Environmental science extraction: ecosystems, conservation, climate"
  - "@textbook-parser Engineering design extraction: specifications, constraints, trade-offs"
  - "@textbook-parser Architecture extraction: structural principles, design elements, styles"
  - "@textbook-parser Agricultural science extraction: crop management, soil science, genetics"
  - "@textbook-parser Veterinary medicine extraction: animal diseases, treatments, procedures"
  - "@textbook-parser Nursing extraction: patient care protocols, nursing theories"
  - "@textbook-parser Public health extraction: epidemiology, interventions, health systems"
  - "@textbook-parser Nutrition extraction: dietary guidelines, metabolism, nutritional needs"
  - "@textbook-parser Sports science extraction: training principles, biomechanics, physiology"
  - "@textbook-parser Education theory extraction: pedagogical approaches, assessment methods"
  - "@textbook-parser Business strategy extraction: frameworks, case analyses, tools"
  - "@textbook-parser Marketing extraction: consumer behavior, segmentation, campaigns"
  - "@textbook-parser Finance extraction: valuation models, portfolio theory, derivatives"
  - "@textbook-parser Accounting extraction: standards, statements, analysis techniques"
  - "@textbook-parser Operations management extraction: process optimization, quality control"
  - "@textbook-parser Human resources extraction: recruitment, development, compensation"
  - "@textbook-parser Project management extraction: methodologies, tools, best practices"
  - "@textbook-parser Quality assurance extraction: testing approaches, metrics, standards"
  - "@textbook-parser OCR preprocessing: clean scanned textbooks, fix OCR errors, validate extraction"
  - "@textbook-parser Format conversion: PDF to structured data (JSON/XML/Markdown)"
  - "@textbook-parser Layout analysis: understand textbook structure, section hierarchies"
  - "@textbook-parser Reference resolution: link citations to bibliography, cross-references"
  - "@textbook-parser Copyright compliance: extract only fair use amounts, track sources"
  - "@textbook-parser Quality control: validate extractions, flag errors, manual review queue"
  - "@textbook-parser Batch processing: parallel extraction from hundreds of textbooks"
  - "@textbook-parser Incremental updates: track textbook editions, extract only changes"
  - "@textbook-parser Integration pipeline: connect to AKU creation workflow"
  - "@textbook-parser Extraction metrics: measure completeness, accuracy, processing time"
  - "@textbook-parser Continuous improvement: refine extraction algorithms based on feedback and error analysis"
  - "@textbook-parser Quality assurance: validate extractions, maintain high accuracy, human review when needed"
  - "@textbook-parser Scale and efficiency: process large volumes while maintaining quality standards"
