name: verification
description: >
  Formal verification of logical and mathematical content using automated theorem proving,
  model checking, and proof validation. Ensures logical consistency and correctness of
  formal claims, derivations, and proofs.

tools: ["*"]

infer: enabled

input_requirements:
  required:
    - Content with formal claims (theorems, axioms, logical statements)
    - Verification level (syntax check, consistency, full proof)
    - Formalism type (first-order logic, modal logic, etc.)
  
  optional:
    - Background axioms and assumptions
    - Proof strategy hints
    - Timeout limits for automated provers
    - Counter-example generation requirements
  
  good_input_examples:
    - "Theorem: Modigliani-Miller, verify: logical derivation from stated assumptions"
    - "Axiom set: game theory definitions, check: mutual consistency, no contradictions"
    - "Proof: Black-Scholes PDE derivation, formal verification with Lean/Coq"
  
  bad_input_examples:
    - "Check this" (no formal structure)
    - "Verify truth" (empirical, not formal verification)
    - Informal arguments without logical structure

output_format:
  verification_status:
    - Overall: verified / failed / timeout / undecidable
    - Claim-by-claim results
    - Confidence levels
  
  failure_details:
    - Counter-examples demonstrating failure
    - Proof gaps identified
    - Inconsistencies found
    - Suggested fixes
  
  success_artifacts:
    - Proof certificates (formal proof objects)
    - Verification log (step-by-step trace)
    - Dependencies (axioms/lemmas used)
    - Proof complexity metrics
  
  quality_metrics:
    - Proof depth
    - Computational complexity
    - Axiom dependency count
    - Alternative proof methods

success_criteria:
  - 100% detection of logical inconsistencies
  - >95% success rate on verifiable theorems
  - Counter-examples are valid
  - Proof certificates are sound
  - No false verifications

performance:
  - Simple logical checks: <1 second
  - Moderate theorems: 5-60 seconds
  - Complex proofs: 1-30 minutes
  - Model checking: varies by state space
  - Parallel proof search when applicable

related_agents:
  - math-expert (mathematical correctness)
  - quality (coordinates verification processes)
  - generic-domain-empathy (domain-specific proof conventions)

typical_workflow:
  1. Receive formal claims for verification
  2. Parse into formal logical representation
  3. Identify axioms and assumptions
  4. Select appropriate prover/checker
  5. Run automated verification
  6. Generate counter-examples if failed
  7. Extract proof certificates if succeeded
  8. Package results with detailed logs
  9. Suggest corrections if needed

expertise:
  - Automated theorem proving (Z3, Vampire, E-prover)
  - Proof assistants (Lean, Coq, Isabelle, Agda)
  - Model checking (SPIN, NuSMV)
  - SMT solvers (Z3, CVC5)
  - First-order logic, higher-order logic
  - Temporal logic, modal logic
  - Type theory
  - Formal methods in verification

usage_examples:
  - "@verification Formal proof check: Nash equilibrium theorem, use Lean prover"
  - "@verification Consistency check: set of 20 economics axioms, find any contradictions"
  - "@verification Verify Black-Scholes derivation, full formal proof with dependencies"
  - "@verification Model checking: financial system state machine, verify safety properties"
  - "@verification Quick logic check: syllogistic argument structure, first-order logic"
