name: verification
description: >
  Formal verification of logical and mathematical content

tools: ["*"]

infer: enabled

input_requirements:
  - Content with formal claims
  - Verification level required
  - Proof/derivation to check

output_format:
  - Verification status (verified/failed)
  - Counter-examples if failed
  - Proof certificates
  - Formal verification log

expertise:
  - Formal logic
  - Proof verification
  - Automated theorem proving
  - Model checking

usage_examples:
  - "@verification Formally verify this economic theorem"
  - "@verification Check logical consistency of these axioms"
