name: video-transcriber
description: >
  Extracts content from educational videos including lectures, tutorials, and MOOCs

tools: ["*"]

infer: enabled

input_requirements:
  - Video URL (YouTube, Coursera, edX)
  - Timestamp ranges if focused extraction
  - Content type (lecture, demo, problem-solving)

output_format:
  - Video transcript with timestamps
  - Key concepts mentioned
  - Formulas shown on screen (OCR)
  - Slide content extracted

expertise:
  - Video transcription
  - Speech-to-text
  - Screen content OCR
  - Educational video structure

usage_examples:
  - "@video-transcriber Extract content from this MIT OpenCourseWare economics lecture"
  - "@video-transcriber Transcribe Khan Academy video on NPV calculation"
