name: video-transcriber
description: >
  Extracts and structures content from educational videos including lectures, tutorials,
  demonstrations, and online courses (MOOCs). Combines speech transcription, screen OCR,
  and semantic analysis to create comprehensive knowledge artifacts.

tools: ["*"]

infer: enabled

input_requirements:
  required:
    - Video source (URL, file path, or streaming link)
    - Subject domain classification
    - Content type (lecture, tutorial, demonstration, interview)
  
  optional:
    - Timestamp ranges for focused extraction
    - Speaker identification needs
    - Slide/screen capture requirements
    - Audio quality assessment
    - Language specification
  
  good_input_examples:
    - "YouTube: https://youtube.com/watch?v=abc123, domain: economics, type: lecture, extract: formulas and key concepts"
    - "Coursera video file: corporate_finance_week3.mp4, timestamps: 10:30-45:00, focus: NPV examples"
    - "MIT OCW: Linear Algebra lecture 15, extract all board work and definitions"
  
  bad_input_examples:
    - "Transcribe this" (no source, no context)
    - "Get the video stuff" (vague, no classification)
    - Low-quality audio without specifying language/domain

output_format:
  transcript:
    - Full timestamped transcript (sentence-level granularity)
    - Speaker diarization if multiple speakers
    - Confidence scores per segment
    - Non-verbal annotations (pauses, emphasis, board pointing)
  
  visual_content:
    - Slides/screen captures with OCR text
    - Board work and handwritten content (mathpix OCR)
    - Diagrams and figures extracted
    - Visual annotations synchronized with audio
  
  semantic_structure:
    - Topic segmentation (when topics change)
    - Key concepts mentioned with timestamps
    - Definitions and theorems highlighted
    - Formulas in LaTeX format
    - Examples and case studies identified
    - Q&A segments separated
  
  metadata:
    - Video duration and quality metrics
    - Speaker information (if known)
    - Language detected
    - Technical quality indicators
    - Extraction timestamp

success_criteria:
  - >95% transcription accuracy for clear audio
  - >85% formula recognition from screen/board
  - Topic segmentation with <5% boundary errors
  - All visual content extracted and synchronized
  - Key concepts identified with >90% recall

performance:
  - Typical: 10x realtime (10min video in 1min processing)
  - High-quality audio: 15x realtime
  - Poor audio/multiple speakers: 5x realtime
  - Screen OCR adds ~2x overhead
  - Parallel processing for long videos

related_agents:
  - formula-extractor (validates extracted formulas)
  - definition-extractor (refines identified definitions)
  - example-extractor (structures worked examples)
  - quality (validates transcription accuracy)
  - citation-extractor (processes references mentioned)

typical_workflow:
  1. Download/access video source
  2. Perform audio extraction and quality assessment
  3. Run speech-to-text transcription with timestamps
  4. Extract keyframes and perform screen OCR
  5. Identify topic boundaries and segment content
  6. Extract formulas, definitions, examples
  7. Synchronize visual and audio elements
  8. Package as structured JSON output
  9. Hand off to domain experts for validation

expertise:
  - Speech recognition (Whisper, Google STT, Azure)
  - Video processing and keyframe extraction
  - OCR for presentations and board work (Tesseract, mathpix)
  - Speaker diarization
  - Educational content structure recognition
  - Multi-modal synchronization
  - Noise reduction and audio enhancement
  - LaTeX formula recognition from images

usage_examples:
  - "@video-transcriber Process MIT 18.06 Linear Algebra Lecture 10, extract all matrix operations and proofs"
  - "@video-transcriber Transcribe Khan Academy NPV tutorial, focus on worked examples with timestamps"
  - "@video-transcriber Extract all slide content from Coursera Corporate Finance Week 3 videos"
  - "@video-transcriber Process YouTube economics lecture playlist (5 videos), create unified concept map"
  - "@video-transcriber Quick transcript only: 3Blue1Brown calculus video, no visual extraction needed"
  - "@video-transcriber Full extraction: Crash Course Chemistry episode, transcript + all diagrams + timestamps"
  - "@video-transcriber Conference presentation: extract slides, speaker notes, and Q&A from academic talk"
  - "@video-transcriber Lecture capture: university physics lecture with board work and demonstrations"
  - "@video-transcriber Tutorial series: extract step-by-step procedures from coding tutorial playlist"
  - "@video-transcriber Documentary: transcribe narration and identify key scenes with descriptions"
  - "@video-transcriber Interview: speaker diarization and question-answer segmentation"
  - "@video-transcriber Podcast with video: audio transcript with show notes and timestamps"
  - "@video-transcriber Animated explainer: transcript + visual elements + timing for recreation"
  - "@video-transcriber Screencas:t software tutorial with mouse clicks and keyboard actions"
  - "@video-transcriber Lab demonstration: procedure steps with safety notes and equipment list"
  - "@video-transcriber Surgical video: procedure steps with anatomical annotations"
  - "@video-transcriber Sports analysis: play-by-play description with tactical diagrams"
  - "@video-transcriber Music lesson: notation extraction from performance video"
  - "@video-transcriber Dance instruction: movement descriptions with counts and positions"
  - "@video-transcriber Art tutorial: technique descriptions with material lists"
  - "@video-transcriber Cooking show: recipe extraction with timing and techniques"
  - "@video-transcriber Foreign language: transcribe with translation and cultural notes"
  - "@video-transcriber Sign language: ASL interpretation to text"
  - "@video-transcriber Captioning: generate SRT/VTT files with proper timing"
  - "@video-transcriber Audio description: describe visual content for blind users"
  - "@video-transcriber Highlight reel: extract key moments based on content analysis"
  - "@video-transcriber Multi-camera: sync transcripts from different angles"
  - "@video-transcriber Live stream: real-time transcription with low latency"
  - "@video-transcriber Poor quality: enhance audio and transcribe challenging recordings"
  - "@video-transcriber Multiple speakers: identify and label each speaker"
  - "@video-transcriber Technical jargon: specialized vocabulary recognition"
  - "@video-transcriber Accents: handle diverse pronunciations and dialects"
  - "@video-transcriber Background noise: filter and transcribe in noisy environments"
  - "@video-transcriber Music detection: separate speech from background music"
  - "@video-transcriber Silence trimming: identify and mark pauses and gaps"
  - "@video-transcriber Filler word removal: clean transcript of ums and ahs"
  - "@video-transcriber Punctuation: add appropriate sentence boundaries"
  - "@video-transcriber Capitalization: proper nouns and sentence starts"
  - "@video-transcriber Number formatting: convert spoken numbers to digits"
  - "@video-transcriber Date formatting: standardize date and time expressions"
  - "@video-transcriber Currency: format monetary amounts correctly"
  - "@video-transcriber Acronym expansion: spell out or provide definitions"
  - "@video-transcriber Technical terms: validate spelling of domain terminology"
  - "@video-transcriber Equation detection: identify spoken mathematics for LaTeX"
  - "@video-transcriber Code detection: recognize programming syntax being discussed"
  - "@video-transcriber URL extraction: capture web addresses mentioned"
  - "@video-transcriber Citation extraction: bibliographic references from lectures"
  - "@video-transcriber Diagram extraction: pull all visual aids from presentations"
  - "@video-transcriber Slide text: OCR text from presentation slides"
  - "@video-transcriber Whiteboard capture: enhance and extract handwritten content"
  - "@video-transcriber Chart data: extract numbers from graphs and tables"
  - "@video-transcriber Formula recognition: mathematical expressions from boards"
  - "@video-transcriber Chemical structure: extract molecular diagrams"
  - "@video-transcriber Circuit diagram: extract electronic schematics"
  - "@video-transcriber Anatomical illustration: medical diagram extraction"
  - "@video-transcriber Geographic map: extract location information"
  - "@video-transcriber Timeline: extract chronological information"
  - "@video-transcriber Flowchart: extract process diagrams"
  - "@video-transcriber Mind map: extract concept relationships"
  - "@video-transcriber Animation: frame-by-frame analysis of motion"
  - "@video-transcriber Demonstration: step-by-step procedure extraction"
  - "@video-transcriber Experiment: protocol and results documentation"
  - "@video-transcriber Survey walkthrough: questionnaire item extraction"
  - "@video-transcriber Software demo: feature descriptions and workflows"
  - "@video-transcriber Product review: specifications and comparisons"
  - "@video-transcriber Unboxing: component identification and assembly"
  - "@video-transcriber Repair guide: troubleshooting steps and solutions"
  - "@video-transcriber Installation: setup instructions with screenshots"
  - "@video-transcriber Tour: location descriptions and navigation"
  - "@video-transcriber Event coverage: highlights and commentary"
  - "@video-transcriber News broadcast: story segmentation and summaries"
  - "@video-transcriber Debate: argument extraction and speaker positions"
  - "@video-transcriber Panel discussion: topic tracking across speakers"
  - "@video-transcriber Q&A session: question-answer pairing"
  - "@video-transcriber Testimony: legal proceeding transcription"
  - "@video-transcriber Meeting minutes: action items and decisions"
  - "@video-transcriber Batch processing: transcribe entire video library with parallel processing and quality control"
