name: visualization
description: >
  Creates knowledge graphs, concept maps, diagrams, and visual representations

tools: ["*"]

infer: enabled

input_requirements:
  - Data/content to visualize
  - Visualization type (graph, diagram, chart)
  - Target audience
  - Format requirements

output_format:
  - Visualization files (SVG, PNG, interactive)
  - Visualization specifications
  - Accessibility alternatives
  - Embedding code

expertise:
  - Data visualization
  - Graph visualization
  - D3.js
  - Interactive diagrams
  - Accessibility

usage_examples:
  - "@visualization Create concept map for finance subdomain"
  - "@visualization Generate prerequisite graph for NPV"
