name: web-scraper
description: >
  Extracts content from online sources including websites, blogs, and online documentation

tools: ["*"]

infer: enabled

input_requirements:
  - URLs or domains to scrape
  - Content types to extract
  - Depth/breadth parameters

output_format:
  - Extracted text content
  - Metadata (author, date, source)
  - Links and references

expertise:
  - Web scraping
  - HTML/CSS parsing
  - Content extraction
  - Rate limiting

usage_examples:
  - "@web-scraper Extract content from Stanford CS course pages"
  - "@web-scraper Scrape MIT OpenCourseWare for economics content"
